### ISSUE TITLE
"Entering Room via Room Picker" test scenario is flaky

### ISSUE THREAD

**Issue by anaulin** [zinc-collective/convene#215]
This seems to be failing about 50% of the time, for me locally and in CI:

```
Scenario: Entering Room via Room Picker from Space Dashboard # features/entering-rooms.feature:14
   ✔ Given the Space Member is on the "System Test" Space Dashboard # features/steps/space_steps.js:4
   ✖ When the Space Member taps the "Listed Room 1" Room in the Room Picker # features/steps/room_steps.js:49
       Error: function timed out, ensure the promise resolves within 20000 milliseconds
           at Timeout._onTimeout (/home/runner/work/convene/convene/node_modules/cucumber/lib/user_code_runner.js:76:18)
           at listOnTimeout (internal/timers.js:554:17)
           at processTimers (internal/timers.js:497:7)
   - Then the Space Member is placed in the "Listed Room 1" Room # features/steps/room_steps.js:53
   ✔ After # features/support/env.js:23
```

**Comment by anaulin** [comment]
I believe this was fixed with the improvements in https://github.com/zinc-collective/convene/pull/216
